on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.10
        with:
          concurrency: 1
          key: docker-cache-v3-{hash}
          restore-keys: |
            docker-cache-v3-

      - run: |
          docker build .
          sleep 90s
