on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: rcowsill/action-docker-layer-caching@fix/85-release
        with:
          concurrency: 1
          key: docker-cache-v5-{hash}
          restore-keys: |
            docker-cache-v5-

      - run: |
          docker build .
          sleep 90s
